# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivadoprojects/armqp/memory_controller_IP_Block/memory_controller_IP_Block.cache/wt [current_project]
set_property parent.project_path D:/vivadoprojects/armqp/memory_controller_IP_Block/memory_controller_IP_Block.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  d:/vivadoprojects/armqp
  d:/vivadoprojects/armqp/ip_repo/armqp_barrelmemorycontroller
} [current_project]
add_files -quiet D:/vivadoprojects/armqp/memory_controller_IP_Block/memory_controller_IP_Block.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files D:/vivadoprojects/armqp/memory_controller_IP_Block/memory_controller_IP_Block.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib D:/vivadoprojects/armqp/src/hdl/barrel_mem_interface.v
synth_design -top barrel_mem_interface -part xc7z020clg484-1
write_checkpoint -noxdef barrel_mem_interface.dcp
catch { report_utilization -file barrel_mem_interface_utilization_synth.rpt -pb barrel_mem_interface_utilization_synth.pb }
