-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.2
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity simpleUpscale is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    videoIn_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    videoIn_TVALID : IN STD_LOGIC;
    videoIn_TREADY : OUT STD_LOGIC;
    videoIn_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    videoIn_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    videoIn_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    videoIn_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    videoIn_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    videoIn_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    videoOut_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    videoOut_TVALID : OUT STD_LOGIC;
    videoOut_TREADY : IN STD_LOGIC;
    videoOut_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    videoOut_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    videoOut_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    videoOut_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    videoOut_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    videoOut_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of simpleUpscale is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "simpleUpscale,hls_ip_2015_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=6.700000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.089000,HLS_SYN_LAT=1083,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=188,HLS_SYN_LUT=226}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_3C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111000000";
    constant ap_const_lv11_438 : STD_LOGIC_VECTOR (10 downto 0) := "10000111000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_437 : STD_LOGIC_VECTOR (10 downto 0) := "10000110111";
    constant ap_const_lv32_77F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000011101111111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal linenum : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_41 : BOOLEAN;
    signal i_1_fu_203_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_51 : BOOLEAN;
    signal exitcond_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_ioackin_videoOut_TREADY : STD_LOGIC;
    signal tmp_5_fu_227_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_bdd_70 : BOOLEAN;
    signal exitcond1_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_76 : BOOLEAN;
    signal tmp_s_fu_270_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_reg_329 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_bdd_90 : BOOLEAN;
    signal linenum_load_3_reg_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_2_reg_138 : STD_LOGIC_VECTOR (10 downto 0);
    signal linenum_load_s_reg_149 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_reg_159 : STD_LOGIC_VECTOR (10 downto 0);
    signal linenum_load_4_reg_170 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_s_fu_281_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st5_fsm_4 : STD_LOGIC;
    signal ap_sig_bdd_120 : BOOLEAN;
    signal tmp_8_fu_209_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_258_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ioackin_videoOut_TREADY : STD_LOGIC := '0';
    signal grp_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);


begin




    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_reg_ioackin_videoOut_TREADY assign process. --
    ap_reg_ioackin_videoOut_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_videoOut_TREADY <= ap_const_logic_0;
            else
                if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0) and not(((exitcond_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY)))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not((ap_sig_bdd_76 or ((ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY) and (ap_const_lv1_0 = exitcond1_fu_221_p2))))))) then 
                    ap_reg_ioackin_videoOut_TREADY <= ap_const_logic_0;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_1 = videoOut_TREADY)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not(ap_sig_bdd_76) and (ap_const_logic_1 = videoOut_TREADY)))) then 
                    ap_reg_ioackin_videoOut_TREADY <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- i_2_reg_138 assign process. --
    i_2_reg_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_fu_191_p2))) then 
                i_2_reg_138 <= ap_const_lv11_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0) and not(((exitcond_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY))))) then 
                i_2_reg_138 <= i_1_fu_203_p2;
            end if; 
        end if;
    end process;

    -- i_reg_159 assign process. --
    i_reg_159_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_const_lv1_0 = tmp_fu_191_p2)))) then 
                i_reg_159 <= ap_const_lv11_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not((ap_sig_bdd_76 or ((ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY) and (ap_const_lv1_0 = exitcond1_fu_221_p2)))))) then 
                i_reg_159 <= tmp_5_fu_227_p2;
            end if; 
        end if;
    end process;

    -- linenum_load_4_reg_170 assign process. --
    linenum_load_4_reg_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_sig_bdd_76 or ((ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY) and (ap_const_lv1_0 = exitcond1_fu_221_p2)))) and not((ap_const_lv1_0 = exitcond1_fu_221_p2)))) then 
                linenum_load_4_reg_170 <= linenum_load_s_reg_149;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not(((exitcond_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY))) and not((exitcond_fu_197_p2 = ap_const_lv1_0)))) then 
                linenum_load_4_reg_170 <= linenum_load_3_reg_128;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then
                linenum <= p_s_fu_281_p3;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0) and not(((exitcond_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY)))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_fu_191_p2)))) then
                linenum_load_3_reg_128 <= linenum;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not((ap_sig_bdd_76 or ((ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY) and (ap_const_lv1_0 = exitcond1_fu_221_p2))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_const_lv1_0 = tmp_fu_191_p2))))) then
                linenum_load_s_reg_149 <= linenum;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then
                tmp_s_reg_329 <= tmp_s_fu_270_p2;
            end if;
        end if;
    end process;

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm, exitcond_fu_197_p2, ap_sig_ioackin_videoOut_TREADY, exitcond1_fu_221_p2, ap_sig_bdd_76, tmp_fu_191_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not((ap_const_lv1_0 = tmp_fu_191_p2))) then
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                end if;
            when ap_ST_st2_fsm_1 => 
                if (((exitcond_fu_197_p2 = ap_const_lv1_0) and not(((exitcond_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY))))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                elsif ((not(((exitcond_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY))) and not((exitcond_fu_197_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                else
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                end if;
            when ap_ST_st3_fsm_2 => 
                if (((ap_const_lv1_0 = exitcond1_fu_221_p2) and not((ap_sig_bdd_76 or ((ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY) and (ap_const_lv1_0 = exitcond1_fu_221_p2)))))) then
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                elsif ((not((ap_sig_bdd_76 or ((ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY) and (ap_const_lv1_0 = exitcond1_fu_221_p2)))) and not((ap_const_lv1_0 = exitcond1_fu_221_p2)))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                else
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                end if;
            when ap_ST_st4_fsm_3 => 
                ap_NS_fsm <= ap_ST_st5_fsm_4;
            when ap_ST_st5_fsm_4 => 
                ap_NS_fsm <= ap_ST_st1_fsm_0;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;

    -- ap_rst_n_inv assign process. --
    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    -- ap_sig_bdd_120 assign process. --
    ap_sig_bdd_120_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_120 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    -- ap_sig_bdd_41 assign process. --
    ap_sig_bdd_41_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_41 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_51 assign process. --
    ap_sig_bdd_51_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_51 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    -- ap_sig_bdd_70 assign process. --
    ap_sig_bdd_70_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_70 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    -- ap_sig_bdd_76 assign process. --
    ap_sig_bdd_76_assign_proc : process(videoIn_TVALID, exitcond1_fu_221_p2)
    begin
                ap_sig_bdd_76 <= ((videoIn_TVALID = ap_const_logic_0) and (ap_const_lv1_0 = exitcond1_fu_221_p2));
    end process;


    -- ap_sig_bdd_90 assign process. --
    ap_sig_bdd_90_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_90 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_41)
    begin
        if (ap_sig_bdd_41) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st2_fsm_1 assign process. --
    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_bdd_51)
    begin
        if (ap_sig_bdd_51) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st3_fsm_2 assign process. --
    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_bdd_70)
    begin
        if (ap_sig_bdd_70) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st4_fsm_3 assign process. --
    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_bdd_90)
    begin
        if (ap_sig_bdd_90) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st5_fsm_4 assign process. --
    ap_sig_cseq_ST_st5_fsm_4_assign_proc : process(ap_sig_bdd_120)
    begin
        if (ap_sig_bdd_120) then 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_ioackin_videoOut_TREADY assign process. --
    ap_sig_ioackin_videoOut_TREADY_assign_proc : process(videoOut_TREADY, ap_reg_ioackin_videoOut_TREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_videoOut_TREADY)) then 
            ap_sig_ioackin_videoOut_TREADY <= videoOut_TREADY;
        else 
            ap_sig_ioackin_videoOut_TREADY <= ap_const_logic_1;
        end if; 
    end process;

    exitcond1_fu_221_p2 <= "1" when (i_reg_159 = ap_const_lv11_438) else "0";
    exitcond_fu_197_p2 <= "1" when (i_2_reg_138 = ap_const_lv11_438) else "0";
    grp_fu_185_p2 <= "1" when (linenum = ap_const_lv32_0) else "0";
    i_1_fu_203_p2 <= std_logic_vector(unsigned(i_2_reg_138) + unsigned(ap_const_lv11_1));
    p_s_fu_281_p3 <= 
        ap_const_lv32_0 when (tmp_1_fu_276_p2(0) = '1') else 
        tmp_s_reg_329;
    tmp_1_fu_276_p2 <= "1" when (signed(tmp_s_reg_329) > signed(ap_const_lv32_77F)) else "0";
    tmp_3_fu_258_p1 <= std_logic_vector(resize(unsigned(grp_fu_185_p2),2));
    tmp_4_fu_263_p2 <= "1" when (i_reg_159 = ap_const_lv11_437) else "0";
    tmp_5_fu_227_p2 <= std_logic_vector(unsigned(i_reg_159) + unsigned(ap_const_lv11_1));
    tmp_8_fu_209_p1 <= std_logic_vector(resize(unsigned(grp_fu_185_p2),2));
    tmp_9_fu_214_p2 <= "1" when (i_2_reg_138 = ap_const_lv11_437) else "0";
    tmp_fu_191_p2 <= "1" when (signed(linenum) < signed(ap_const_lv32_3C0)) else "0";
    tmp_s_fu_270_p2 <= std_logic_vector(unsigned(linenum_load_4_reg_170) + unsigned(ap_const_lv32_1));

    -- videoIn_TREADY assign process. --
    videoIn_TREADY_assign_proc : process(ap_sig_ioackin_videoOut_TREADY, ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_221_p2, ap_sig_bdd_76)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not((ap_sig_bdd_76 or ((ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY) and (ap_const_lv1_0 = exitcond1_fu_221_p2))))))) then 
            videoIn_TREADY <= ap_const_logic_1;
        else 
            videoIn_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    -- videoOut_TDATA assign process. --
    videoOut_TDATA_assign_proc : process(videoIn_TDATA, ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_197_p2, ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_221_p2, ap_sig_bdd_76)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not(ap_sig_bdd_76))) then 
            videoOut_TDATA <= videoIn_TDATA;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0))) then 
            videoOut_TDATA <= ap_const_lv16_0;
        else 
            videoOut_TDATA <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    -- videoOut_TDEST assign process. --
    videoOut_TDEST_assign_proc : process(videoIn_TDEST, ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_197_p2, ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_221_p2, ap_sig_bdd_76)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not(ap_sig_bdd_76))) then 
            videoOut_TDEST <= videoIn_TDEST;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0))) then 
            videoOut_TDEST <= ap_const_lv6_1;
        else 
            videoOut_TDEST <= "XXXXXX";
        end if; 
    end process;


    -- videoOut_TID assign process. --
    videoOut_TID_assign_proc : process(videoIn_TID, ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_197_p2, ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_221_p2, ap_sig_bdd_76)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not(ap_sig_bdd_76))) then 
            videoOut_TID <= videoIn_TID;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0))) then 
            videoOut_TID <= ap_const_lv5_0;
        else 
            videoOut_TID <= "XXXXX";
        end if; 
    end process;


    -- videoOut_TKEEP assign process. --
    videoOut_TKEEP_assign_proc : process(videoIn_TKEEP, ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_197_p2, ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_221_p2, ap_sig_bdd_76)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not(ap_sig_bdd_76))) then 
            videoOut_TKEEP <= videoIn_TKEEP;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0))) then 
            videoOut_TKEEP <= ap_const_lv2_1;
        else 
            videoOut_TKEEP <= "XX";
        end if; 
    end process;


    -- videoOut_TLAST assign process. --
    videoOut_TLAST_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_197_p2, ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_221_p2, ap_sig_bdd_76, tmp_9_fu_214_p2, tmp_4_fu_263_p2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not(ap_sig_bdd_76))) then 
            videoOut_TLAST <= tmp_4_fu_263_p2;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0))) then 
            videoOut_TLAST <= tmp_9_fu_214_p2;
        else 
            videoOut_TLAST <= "X";
        end if; 
    end process;


    -- videoOut_TSTRB assign process. --
    videoOut_TSTRB_assign_proc : process(videoIn_TSTRB, ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_197_p2, ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_221_p2, ap_sig_bdd_76)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not(ap_sig_bdd_76))) then 
            videoOut_TSTRB <= videoIn_TSTRB;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0))) then 
            videoOut_TSTRB <= ap_const_lv2_1;
        else 
            videoOut_TSTRB <= "XX";
        end if; 
    end process;


    -- videoOut_TUSER assign process. --
    videoOut_TUSER_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_197_p2, ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_221_p2, ap_sig_bdd_76, tmp_8_fu_209_p1, tmp_3_fu_258_p1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not(ap_sig_bdd_76))) then 
            videoOut_TUSER <= tmp_3_fu_258_p1;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0))) then 
            videoOut_TUSER <= tmp_8_fu_209_p1;
        else 
            videoOut_TUSER <= "XX";
        end if; 
    end process;


    -- videoOut_TVALID assign process. --
    videoOut_TVALID_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_197_p2, ap_sig_cseq_ST_st3_fsm_2, exitcond1_fu_221_p2, ap_sig_bdd_76, ap_reg_ioackin_videoOut_TREADY)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_reg_ioackin_videoOut_TREADY)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_221_p2) and not(ap_sig_bdd_76) and (ap_const_logic_0 = ap_reg_ioackin_videoOut_TREADY)))) then 
            videoOut_TVALID <= ap_const_logic_1;
        else 
            videoOut_TVALID <= ap_const_logic_0;
        end if; 
    end process;

end behav;
