// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rotatedUpscale,hls_ip_2015_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=6.734010,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.562000,HLS_SYN_LAT=2186,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=11,HLS_SYN_FF=1425,HLS_SYN_LUT=2289}" *)

module rotatedUpscale (
        ap_clk,
        ap_rst_n,
        vidInput_TDATA,
        vidInput_TVALID,
        vidInput_TREADY,
        vidInput_TKEEP,
        vidInput_TSTRB,
        vidInput_TUSER,
        vidInput_TLAST,
        vidInput_TID,
        vidInput_TDEST,
        vidOutput_TDATA,
        vidOutput_TVALID,
        vidOutput_TREADY,
        vidOutput_TKEEP,
        vidOutput_TSTRB,
        vidOutput_TUSER,
        vidOutput_TLAST,
        vidOutput_TID,
        vidOutput_TDEST
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 4'b10;
parameter    ap_ST_pp1_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st29_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv12_438 = 12'b10000111000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv16_FFFF = 16'b1111111111111111;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv64_3FD2F684BDA12F68 = 64'b11111111010010111101101000010010111101101000010010111101101000;
parameter    ap_const_lv11_438 = 11'b10000111000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_34 = 32'b110100;
parameter    ap_const_lv32_3E = 32'b111110;
parameter    ap_const_lv12_C01 = 12'b110000000001;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv11_3FF = 11'b1111111111;
parameter    ap_const_lv32_53 = 32'b1010011;
parameter    ap_const_lv11_437 = 11'b10000110111;
parameter    ap_const_lv12_870 = 12'b100001110000;
parameter    ap_const_lv11_3C8 = 11'b1111001000;
parameter    ap_const_lv12_86F = 12'b100001101111;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv32_3BF = 32'b1110111111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst_n;
input  [15:0] vidInput_TDATA;
input   vidInput_TVALID;
output   vidInput_TREADY;
input  [1:0] vidInput_TKEEP;
input  [1:0] vidInput_TSTRB;
input  [1:0] vidInput_TUSER;
input  [0:0] vidInput_TLAST;
input  [4:0] vidInput_TID;
input  [5:0] vidInput_TDEST;
output  [15:0] vidOutput_TDATA;
output   vidOutput_TVALID;
input   vidOutput_TREADY;
output  [1:0] vidOutput_TKEEP;
output  [1:0] vidOutput_TSTRB;
output  [1:0] vidOutput_TUSER;
output  [0:0] vidOutput_TLAST;
output  [4:0] vidOutput_TID;
output  [5:0] vidOutput_TDEST;

reg vidInput_TREADY;
reg vidOutput_TVALID;
reg[1:0] vidOutput_TUSER;
reg[0:0] vidOutput_TLAST;
reg    ap_rst_n_inv;
reg   [31:0] line_r = 32'b00000000000000000000000000000000;
reg   [10:0] j_reg_235;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it1;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_bdd_42;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg    ap_reg_ppiten_pp0_it9 = 1'b0;
reg    ap_reg_ppiten_pp0_it10 = 1'b0;
reg    ap_reg_ppiten_pp0_it11 = 1'b0;
reg    ap_reg_ppiten_pp0_it12 = 1'b0;
reg    ap_reg_ppiten_pp0_it13 = 1'b0;
reg    ap_reg_ppiten_pp0_it14 = 1'b0;
reg    ap_reg_ppiten_pp0_it15 = 1'b0;
reg    ap_reg_ppiten_pp0_it16 = 1'b0;
reg    ap_reg_ppiten_pp0_it17 = 1'b0;
reg    ap_reg_ppiten_pp0_it18 = 1'b0;
reg    ap_reg_ppiten_pp0_it19 = 1'b0;
reg    ap_reg_ppiten_pp0_it20 = 1'b0;
reg   [0:0] tmp_reg_631;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it20;
reg   [0:0] tmp_4_reg_682;
reg   [0:0] tmp_5_reg_686;
reg    ap_sig_bdd_102;
reg    ap_reg_ppiten_pp0_it21 = 1'b0;
reg    ap_reg_ppiten_pp0_it22 = 1'b0;
reg    ap_reg_ppiten_pp0_it23 = 1'b0;
reg   [0:0] exitcond1_reg_622;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it23;
reg    ap_sig_ioackin_vidOutput_TREADY;
reg    ap_reg_ppiten_pp0_it24 = 1'b0;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it2;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it3;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it4;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it5;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it6;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it7;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it8;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it9;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it10;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it11;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it12;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it13;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it14;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it15;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it16;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it17;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it18;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it19;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it20;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it21;
reg   [10:0] ap_reg_ppstg_j_reg_235_pp0_it22;
reg   [11:0] j1_reg_247;
wire   [0:0] exitcond1_fu_298_p2;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it5;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it6;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it7;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it8;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it9;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it10;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it11;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it12;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it13;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it14;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it15;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it16;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it17;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it18;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it19;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it20;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it21;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_622_pp0_it22;
wire   [10:0] j_2_fu_304_p2;
reg   [10:0] j_2_reg_626;
wire   [0:0] tmp_fu_310_p1;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it3;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it4;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it5;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it6;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it7;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it8;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it9;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it10;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it11;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it12;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it13;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it14;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it15;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it16;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it17;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it18;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it19;
reg   [0:0] ap_reg_ppstg_tmp_reg_631_pp0_it21;
wire   [63:0] grp_fu_263_p1;
reg   [63:0] tmp_2_reg_640;
wire   [63:0] grp_fu_258_p2;
reg   [63:0] x_assign_reg_645;
reg   [0:0] p_Result_s_reg_650;
reg   [0:0] ap_reg_ppstg_p_Result_s_reg_650_pp0_it18;
wire   [51:0] loc_V_1_fu_340_p1;
reg   [51:0] loc_V_1_reg_655;
wire   [0:0] isNeg_fu_354_p3;
reg   [0:0] isNeg_reg_660;
wire   [11:0] sh_assign_1_fu_372_p3;
reg   [11:0] sh_assign_1_reg_665;
wire   [31:0] p_Val2_4_fu_436_p3;
reg   [31:0] p_Val2_4_reg_670;
wire   [31:0] p_Val2_s_fu_448_p3;
reg   [31:0] p_Val2_s_reg_676;
wire   [0:0] tmp_4_fu_454_p2;
wire   [0:0] tmp_5_fu_466_p2;
wire   [0:0] tmp_17_fu_510_p2;
reg   [0:0] tmp_17_reg_695;
wire   [0:0] exitcond_fu_533_p2;
reg   [0:0] exitcond_reg_700;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_2;
reg    ap_sig_bdd_262;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
wire   [0:0] tmp_10_fu_554_p2;
reg   [0:0] tmp_10_reg_709;
wire   [11:0] j_1_fu_560_p2;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_288;
reg   [10:0] data_V_address0;
reg    data_V_ce0;
reg    data_V_we0;
reg   [15:0] data_V_d0;
reg   [10:0] data_V_address1;
reg    data_V_ce1;
wire   [15:0] data_V_q1;
reg   [10:0] j_phi_fu_239_p4;
wire   [63:0] tmp_13_fu_491_p1;
wire   [63:0] tmp_12_fu_500_p1;
wire   [63:0] tmp_14_fu_505_p1;
wire   [63:0] tmp_9_fu_549_p1;
wire   [31:0] tmp_18_fu_521_p2;
wire   [31:0] tmp_11_fu_571_p2;
reg    ap_sig_cseq_ST_st29_fsm_3;
reg    ap_sig_bdd_342;
wire   [0:0] tmp_6_fu_583_p2;
reg   [31:0] prevIndex_1_fu_132;
reg   [31:0] prevIndex_fu_136;
reg   [15:0] prevVal1_V_fu_140;
reg   [15:0] prevVal2_V_fu_144;
wire   [1:0] tmp_16_fu_516_p1;
wire   [1:0] tmp_3_fu_566_p1;
reg    ap_reg_ioackin_vidOutput_TREADY = 1'b0;
wire   [63:0] grp_fu_258_p0;
wire   [63:0] grp_fu_258_p1;
wire   [31:0] grp_fu_263_p0;
wire   [63:0] p_Val2_1_fu_319_p1;
wire   [10:0] loc_V_fu_330_p4;
wire   [11:0] tmp_i_i_i_cast2_fu_344_p1;
wire  signed [11:0] sh_assign_fu_348_p2;
wire   [10:0] tmp_i_i_11_fu_362_p2;
wire  signed [11:0] tmp_i_i_cast_fu_368_p1;
wire   [52:0] p_Result_1_fu_380_p3;
wire  signed [31:0] sh_assign_1_cast_fu_391_p1;
wire   [52:0] tmp_1_i_i_cast_fu_398_p1;
wire   [135:0] tmp_i_i_fu_387_p1;
wire   [135:0] tmp_1_i_i_fu_394_p1;
wire   [52:0] tmp_2_i_i_fu_402_p2;
wire   [0:0] tmp_25_fu_414_p3;
wire   [135:0] tmp_4_i_i_fu_408_p2;
wire   [31:0] tmp_19_fu_422_p1;
wire   [31:0] tmp_20_fu_426_p4;
wire   [31:0] p_Val2_7_i_i_fu_443_p2;
wire   [0:0] grp_fu_277_p2;
wire   [10:0] tmp_21_fu_539_p1;
wire   [10:0] tmp_8_fu_543_p2;
reg    grp_fu_258_ce;
reg    grp_fu_263_ce;
reg   [3:0] ap_NS_fsm;


rotatedUpscale_data_V #(
    .DataWidth( 16 ),
    .AddressRange( 1080 ),
    .AddressWidth( 11 ))
data_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( data_V_address0 ),
    .ce0( data_V_ce0 ),
    .we0( data_V_we0 ),
    .d0( data_V_d0 ),
    .address1( data_V_address1 ),
    .ce1( data_V_ce1 ),
    .q1( data_V_q1 )
);

rotatedUpscale_dmul_64ns_64ns_64_9_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
rotatedUpscale_dmul_64ns_64ns_64_9_max_dsp_U0(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_258_p0 ),
    .din1( grp_fu_258_p1 ),
    .ce( grp_fu_258_ce ),
    .dout( grp_fu_258_p2 )
);

rotatedUpscale_sitodp_32ns_64_8 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
rotatedUpscale_sitodp_32ns_64_8_U1(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_263_p0 ),
    .ce( grp_fu_263_ce ),
    .dout( grp_fu_263_p1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_vidOutput_TREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_vidOutput_TREADY
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_vidOutput_TREADY <= ap_const_logic_0;
    end else begin
        if ((((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
            ap_reg_ioackin_vidOutput_TREADY <= ap_const_logic_0;
        end else if ((((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24) & ~(ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) & (ap_const_logic_1 == vidOutput_TREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_1 == vidOutput_TREADY)))) begin
            ap_reg_ioackin_vidOutput_TREADY <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == exitcond1_fu_298_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == exitcond1_fu_298_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == exitcond1_fu_298_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it10 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it10
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it10 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it10 <= ap_reg_ppiten_pp0_it9;
        end
    end
end

/// ap_reg_ppiten_pp0_it11 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it11
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it11 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it11 <= ap_reg_ppiten_pp0_it10;
        end
    end
end

/// ap_reg_ppiten_pp0_it12 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it12
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it12 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it12 <= ap_reg_ppiten_pp0_it11;
        end
    end
end

/// ap_reg_ppiten_pp0_it13 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it13
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it13 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it13 <= ap_reg_ppiten_pp0_it12;
        end
    end
end

/// ap_reg_ppiten_pp0_it14 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it14
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it14 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it14 <= ap_reg_ppiten_pp0_it13;
        end
    end
end

/// ap_reg_ppiten_pp0_it15 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it15
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it15 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it15 <= ap_reg_ppiten_pp0_it14;
        end
    end
end

/// ap_reg_ppiten_pp0_it16 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it16
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it16 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it16 <= ap_reg_ppiten_pp0_it15;
        end
    end
end

/// ap_reg_ppiten_pp0_it17 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it17
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it17 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it17 <= ap_reg_ppiten_pp0_it16;
        end
    end
end

/// ap_reg_ppiten_pp0_it18 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it18
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it18 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it18 <= ap_reg_ppiten_pp0_it17;
        end
    end
end

/// ap_reg_ppiten_pp0_it19 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it19
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it19 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it19 <= ap_reg_ppiten_pp0_it18;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it20 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it20
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it20 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it20 <= ap_reg_ppiten_pp0_it19;
        end
    end
end

/// ap_reg_ppiten_pp0_it21 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it21
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it21 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it21 <= ap_reg_ppiten_pp0_it20;
        end
    end
end

/// ap_reg_ppiten_pp0_it22 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it22
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it22 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it22 <= ap_reg_ppiten_pp0_it21;
        end
    end
end

/// ap_reg_ppiten_pp0_it23 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it23
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it23 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it23 <= ap_reg_ppiten_pp0_it22;
        end
    end
end

/// ap_reg_ppiten_pp0_it24 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it24
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it24 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it24 <= ap_reg_ppiten_pp0_it23;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
            ap_reg_ppiten_pp0_it24 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

/// ap_reg_ppiten_pp0_it8 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

/// ap_reg_ppiten_pp0_it9 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it9
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end
    end
end

/// ap_reg_ppiten_pp1_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond_fu_533_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == exitcond1_fu_298_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp1_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond_fu_533_p2))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == exitcond1_fu_298_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond_fu_533_p2)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == exitcond1_fu_298_p2))) begin
        j1_reg_247 <= ap_const_lv12_438;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond_fu_533_p2))) begin
        j1_reg_247 <= j_1_fu_560_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        j_reg_235 <= ap_const_lv11_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == exitcond1_reg_622))) begin
        j_reg_235 <= j_2_reg_626;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st29_fsm_3) & ~(ap_const_lv1_0 == tmp_6_fu_583_p2))) begin
        line_r <= ap_const_lv32_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        line_r <= tmp_11_fu_571_p2;
    end else if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))))) begin
        line_r <= tmp_18_fu_521_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it20) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it19) & (ap_const_lv1_0 == tmp_5_fu_466_p2))) begin
        prevIndex_fu_136 <= prevIndex_1_fu_132;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        prevIndex_fu_136 <= ap_const_lv32_FFFFFFFF;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_reg_ppstg_tmp_reg_631_pp0_it20 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_4_reg_682) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))))) begin
        prevVal1_V_fu_140 <= vidInput_TDATA;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        prevVal1_V_fu_140 <= ap_const_lv16_FFFF;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_reg_ppstg_tmp_reg_631_pp0_it20 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_5_reg_686) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))))) begin
        prevVal2_V_fu_144 <= vidInput_TDATA;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        prevVal2_V_fu_144 <= ap_const_lv16_FFFF;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))))) begin
        ap_reg_ppstg_exitcond1_reg_622_pp0_it1 <= exitcond1_reg_622;
        ap_reg_ppstg_j_reg_235_pp0_it1 <= j_reg_235;
        ap_reg_ppstg_tmp_reg_631_pp0_it1 <= tmp_reg_631;
        exitcond1_reg_622 <= exitcond1_fu_298_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) begin
        ap_reg_ppstg_exitcond1_reg_622_pp0_it10 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it9;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it11 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it10;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it12 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it11;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it13 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it12;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it14 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it13;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it15 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it14;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it16 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it15;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it17 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it16;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it18 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it17;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it19 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it18;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it2 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it1;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it20 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it19;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it21 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it20;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it22 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it21;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it23 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it22;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it3 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it2;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it4 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it3;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it5 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it4;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it6 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it5;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it7 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it6;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it8 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it7;
        ap_reg_ppstg_exitcond1_reg_622_pp0_it9 <= ap_reg_ppstg_exitcond1_reg_622_pp0_it8;
        ap_reg_ppstg_j_reg_235_pp0_it10 <= ap_reg_ppstg_j_reg_235_pp0_it9;
        ap_reg_ppstg_j_reg_235_pp0_it11 <= ap_reg_ppstg_j_reg_235_pp0_it10;
        ap_reg_ppstg_j_reg_235_pp0_it12 <= ap_reg_ppstg_j_reg_235_pp0_it11;
        ap_reg_ppstg_j_reg_235_pp0_it13 <= ap_reg_ppstg_j_reg_235_pp0_it12;
        ap_reg_ppstg_j_reg_235_pp0_it14 <= ap_reg_ppstg_j_reg_235_pp0_it13;
        ap_reg_ppstg_j_reg_235_pp0_it15 <= ap_reg_ppstg_j_reg_235_pp0_it14;
        ap_reg_ppstg_j_reg_235_pp0_it16 <= ap_reg_ppstg_j_reg_235_pp0_it15;
        ap_reg_ppstg_j_reg_235_pp0_it17 <= ap_reg_ppstg_j_reg_235_pp0_it16;
        ap_reg_ppstg_j_reg_235_pp0_it18 <= ap_reg_ppstg_j_reg_235_pp0_it17;
        ap_reg_ppstg_j_reg_235_pp0_it19 <= ap_reg_ppstg_j_reg_235_pp0_it18;
        ap_reg_ppstg_j_reg_235_pp0_it2 <= ap_reg_ppstg_j_reg_235_pp0_it1;
        ap_reg_ppstg_j_reg_235_pp0_it20 <= ap_reg_ppstg_j_reg_235_pp0_it19;
        ap_reg_ppstg_j_reg_235_pp0_it21 <= ap_reg_ppstg_j_reg_235_pp0_it20;
        ap_reg_ppstg_j_reg_235_pp0_it22 <= ap_reg_ppstg_j_reg_235_pp0_it21;
        ap_reg_ppstg_j_reg_235_pp0_it3 <= ap_reg_ppstg_j_reg_235_pp0_it2;
        ap_reg_ppstg_j_reg_235_pp0_it4 <= ap_reg_ppstg_j_reg_235_pp0_it3;
        ap_reg_ppstg_j_reg_235_pp0_it5 <= ap_reg_ppstg_j_reg_235_pp0_it4;
        ap_reg_ppstg_j_reg_235_pp0_it6 <= ap_reg_ppstg_j_reg_235_pp0_it5;
        ap_reg_ppstg_j_reg_235_pp0_it7 <= ap_reg_ppstg_j_reg_235_pp0_it6;
        ap_reg_ppstg_j_reg_235_pp0_it8 <= ap_reg_ppstg_j_reg_235_pp0_it7;
        ap_reg_ppstg_j_reg_235_pp0_it9 <= ap_reg_ppstg_j_reg_235_pp0_it8;
        ap_reg_ppstg_p_Result_s_reg_650_pp0_it18 <= p_Result_s_reg_650;
        ap_reg_ppstg_tmp_reg_631_pp0_it10 <= ap_reg_ppstg_tmp_reg_631_pp0_it9;
        ap_reg_ppstg_tmp_reg_631_pp0_it11 <= ap_reg_ppstg_tmp_reg_631_pp0_it10;
        ap_reg_ppstg_tmp_reg_631_pp0_it12 <= ap_reg_ppstg_tmp_reg_631_pp0_it11;
        ap_reg_ppstg_tmp_reg_631_pp0_it13 <= ap_reg_ppstg_tmp_reg_631_pp0_it12;
        ap_reg_ppstg_tmp_reg_631_pp0_it14 <= ap_reg_ppstg_tmp_reg_631_pp0_it13;
        ap_reg_ppstg_tmp_reg_631_pp0_it15 <= ap_reg_ppstg_tmp_reg_631_pp0_it14;
        ap_reg_ppstg_tmp_reg_631_pp0_it16 <= ap_reg_ppstg_tmp_reg_631_pp0_it15;
        ap_reg_ppstg_tmp_reg_631_pp0_it17 <= ap_reg_ppstg_tmp_reg_631_pp0_it16;
        ap_reg_ppstg_tmp_reg_631_pp0_it18 <= ap_reg_ppstg_tmp_reg_631_pp0_it17;
        ap_reg_ppstg_tmp_reg_631_pp0_it19 <= ap_reg_ppstg_tmp_reg_631_pp0_it18;
        ap_reg_ppstg_tmp_reg_631_pp0_it2 <= ap_reg_ppstg_tmp_reg_631_pp0_it1;
        ap_reg_ppstg_tmp_reg_631_pp0_it20 <= ap_reg_ppstg_tmp_reg_631_pp0_it19;
        ap_reg_ppstg_tmp_reg_631_pp0_it21 <= ap_reg_ppstg_tmp_reg_631_pp0_it20;
        ap_reg_ppstg_tmp_reg_631_pp0_it3 <= ap_reg_ppstg_tmp_reg_631_pp0_it2;
        ap_reg_ppstg_tmp_reg_631_pp0_it4 <= ap_reg_ppstg_tmp_reg_631_pp0_it3;
        ap_reg_ppstg_tmp_reg_631_pp0_it5 <= ap_reg_ppstg_tmp_reg_631_pp0_it4;
        ap_reg_ppstg_tmp_reg_631_pp0_it6 <= ap_reg_ppstg_tmp_reg_631_pp0_it5;
        ap_reg_ppstg_tmp_reg_631_pp0_it7 <= ap_reg_ppstg_tmp_reg_631_pp0_it6;
        ap_reg_ppstg_tmp_reg_631_pp0_it8 <= ap_reg_ppstg_tmp_reg_631_pp0_it7;
        ap_reg_ppstg_tmp_reg_631_pp0_it9 <= ap_reg_ppstg_tmp_reg_631_pp0_it8;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
        exitcond_reg_700 <= exitcond_fu_533_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it16))) begin
        isNeg_reg_660 <= sh_assign_fu_348_p2[ap_const_lv32_B];
        loc_V_1_reg_655 <= loc_V_1_fu_340_p1;
        p_Result_s_reg_650 <= p_Val2_1_fu_319_p1[ap_const_lv32_3F];
        sh_assign_1_reg_665 <= sh_assign_1_fu_372_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))))) begin
        j_2_reg_626 <= j_2_fu_304_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it17))) begin
        p_Val2_4_reg_670 <= p_Val2_4_fu_436_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it18))) begin
        p_Val2_s_reg_676 <= p_Val2_s_fu_448_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it20) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it19))) begin
        prevIndex_1_fu_132 <= p_Val2_s_reg_676;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & (ap_const_lv1_0 == exitcond_fu_533_p2))) begin
        tmp_10_reg_709 <= tmp_10_fu_554_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it22))) begin
        tmp_17_reg_695 <= tmp_17_fu_510_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it6))) begin
        tmp_2_reg_640 <= grp_fu_263_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it19))) begin
        tmp_4_reg_682 <= tmp_4_fu_454_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it19))) begin
        tmp_5_reg_686 <= tmp_5_fu_466_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == exitcond1_fu_298_p2))) begin
        tmp_reg_631 <= tmp_fu_310_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it15))) begin
        x_assign_reg_645 <= grp_fu_258_p2;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_1 assign process. ///
always @ (ap_sig_bdd_42)
begin
    if (ap_sig_bdd_42) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp1_stg0_fsm_2 assign process. ///
always @ (ap_sig_bdd_262)
begin
    if (ap_sig_bdd_262) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_288)
begin
    if (ap_sig_bdd_288) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st29_fsm_3 assign process. ///
always @ (ap_sig_bdd_342)
begin
    if (ap_sig_bdd_342) begin
        ap_sig_cseq_ST_st29_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st29_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_ioackin_vidOutput_TREADY assign process. ///
always @ (vidOutput_TREADY or ap_reg_ioackin_vidOutput_TREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_vidOutput_TREADY)) begin
        ap_sig_ioackin_vidOutput_TREADY = vidOutput_TREADY;
    end else begin
        ap_sig_ioackin_vidOutput_TREADY = ap_const_logic_1;
    end
end

/// data_V_address0 assign process. ///
always @ (ap_reg_ppiten_pp0_it22 or ap_reg_ppstg_tmp_reg_631_pp0_it21 or tmp_13_fu_491_p1 or tmp_12_fu_500_p1)
begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it22)) begin
        if (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it21)) begin
            data_V_address0 = tmp_12_fu_500_p1;
        end else if ((ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it21)) begin
            data_V_address0 = tmp_13_fu_491_p1;
        end else begin
            data_V_address0 = 'bx;
        end
    end else begin
        data_V_address0 = 'bx;
    end
end

/// data_V_address1 assign process. ///
always @ (ap_reg_ppiten_pp0_it23 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it0 or tmp_14_fu_505_p1 or tmp_9_fu_549_p1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0))) begin
        data_V_address1 = tmp_9_fu_549_p1;
    end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it23)) begin
        data_V_address1 = tmp_14_fu_505_p1;
    end else begin
        data_V_address1 = 'bx;
    end
end

/// data_V_ce0 assign process. ///
always @ (ap_sig_bdd_102 or ap_reg_ppiten_pp0_it21 or ap_reg_ppiten_pp0_it22 or ap_reg_ppstg_exitcond1_reg_622_pp0_it23 or ap_sig_ioackin_vidOutput_TREADY or ap_reg_ppiten_pp0_it24 or ap_reg_ppstg_tmp_reg_631_pp0_it21)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it22) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it21)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it22) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it21)))) begin
        data_V_ce0 = ap_const_logic_1;
    end else begin
        data_V_ce0 = ap_const_logic_0;
    end
end

/// data_V_ce1 assign process. ///
always @ (ap_sig_bdd_102 or ap_reg_ppiten_pp0_it21 or ap_reg_ppiten_pp0_it23 or ap_reg_ppstg_exitcond1_reg_622_pp0_it23 or ap_sig_ioackin_vidOutput_TREADY or ap_reg_ppiten_pp0_it24 or exitcond_reg_700 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it23) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))))) begin
        data_V_ce1 = ap_const_logic_1;
    end else begin
        data_V_ce1 = ap_const_logic_0;
    end
end

/// data_V_d0 assign process. ///
always @ (ap_reg_ppiten_pp0_it22 or ap_reg_ppstg_tmp_reg_631_pp0_it21 or prevVal1_V_fu_140 or prevVal2_V_fu_144)
begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it22)) begin
        if (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it21)) begin
            data_V_d0 = prevVal2_V_fu_144;
        end else if ((ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it21)) begin
            data_V_d0 = prevVal1_V_fu_140;
        end else begin
            data_V_d0 = 'bx;
        end
    end else begin
        data_V_d0 = 'bx;
    end
end

/// data_V_we0 assign process. ///
always @ (ap_sig_bdd_102 or ap_reg_ppiten_pp0_it21 or ap_reg_ppiten_pp0_it22 or ap_reg_ppstg_exitcond1_reg_622_pp0_it23 or ap_sig_ioackin_vidOutput_TREADY or ap_reg_ppiten_pp0_it24 or ap_reg_ppstg_tmp_reg_631_pp0_it21)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it22) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it21)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it22) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_631_pp0_it21)))) begin
        data_V_we0 = ap_const_logic_1;
    end else begin
        data_V_we0 = ap_const_logic_0;
    end
end

/// grp_fu_258_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_sig_bdd_102 or ap_reg_ppiten_pp0_it21 or ap_reg_ppstg_exitcond1_reg_622_pp0_it23 or ap_sig_ioackin_vidOutput_TREADY or ap_reg_ppiten_pp0_it24)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))))) begin
        grp_fu_258_ce = ap_const_logic_1;
    end else begin
        grp_fu_258_ce = ap_const_logic_0;
    end
end

/// grp_fu_263_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_sig_bdd_102 or ap_reg_ppiten_pp0_it21 or ap_reg_ppstg_exitcond1_reg_622_pp0_it23 or ap_sig_ioackin_vidOutput_TREADY or ap_reg_ppiten_pp0_it24)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))))) begin
        grp_fu_263_ce = ap_const_logic_1;
    end else begin
        grp_fu_263_ce = ap_const_logic_0;
    end
end

/// j_phi_fu_239_p4 assign process. ///
always @ (j_reg_235 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1 or exitcond1_reg_622 or j_2_reg_626)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_lv1_0 == exitcond1_reg_622))) begin
        j_phi_fu_239_p4 = j_2_reg_626;
    end else begin
        j_phi_fu_239_p4 = j_reg_235;
    end
end

/// vidInput_TREADY assign process. ///
always @ (ap_reg_ppstg_tmp_reg_631_pp0_it20 or tmp_4_reg_682 or tmp_5_reg_686 or ap_sig_bdd_102 or ap_reg_ppiten_pp0_it21 or ap_reg_ppstg_exitcond1_reg_622_pp0_it23 or ap_sig_ioackin_vidOutput_TREADY or ap_reg_ppiten_pp0_it24)
begin
    if ((((ap_reg_ppstg_tmp_reg_631_pp0_it20 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_4_reg_682) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))) | (~(ap_reg_ppstg_tmp_reg_631_pp0_it20 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_5_reg_686) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24)))))) begin
        vidInput_TREADY = ap_const_logic_1;
    end else begin
        vidInput_TREADY = ap_const_logic_0;
    end
end

/// vidOutput_TLAST assign process. ///
always @ (ap_sig_bdd_102 or ap_reg_ppiten_pp0_it21 or ap_reg_ppstg_exitcond1_reg_622_pp0_it23 or ap_reg_ppiten_pp0_it24 or tmp_17_reg_695 or exitcond_reg_700 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it1 or tmp_10_reg_709)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        vidOutput_TLAST = tmp_10_reg_709;
    end else if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24) & ~(ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)))) begin
        vidOutput_TLAST = tmp_17_reg_695;
    end else begin
        vidOutput_TLAST = 'bx;
    end
end

/// vidOutput_TUSER assign process. ///
always @ (ap_sig_bdd_102 or ap_reg_ppiten_pp0_it21 or ap_reg_ppstg_exitcond1_reg_622_pp0_it23 or ap_reg_ppiten_pp0_it24 or exitcond_reg_700 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it1 or tmp_16_fu_516_p1 or tmp_3_fu_566_p1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        vidOutput_TUSER = tmp_3_fu_566_p1;
    end else if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24) & ~(ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)))) begin
        vidOutput_TUSER = tmp_16_fu_516_p1;
    end else begin
        vidOutput_TUSER = 'bx;
    end
end

/// vidOutput_TVALID assign process. ///
always @ (ap_sig_bdd_102 or ap_reg_ppiten_pp0_it21 or ap_reg_ppstg_exitcond1_reg_622_pp0_it23 or ap_reg_ppiten_pp0_it24 or exitcond_reg_700 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it1 or ap_reg_ioackin_vidOutput_TREADY)
begin
    if ((((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24) & ~(ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) & (ap_const_logic_0 == ap_reg_ioackin_vidOutput_TREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_logic_0 == ap_reg_ioackin_vidOutput_TREADY)))) begin
        vidOutput_TVALID = ap_const_logic_1;
    end else begin
        vidOutput_TVALID = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_102 or ap_reg_ppiten_pp0_it21 or ap_reg_ppiten_pp0_it23 or ap_reg_ppstg_exitcond1_reg_622_pp0_it23 or ap_sig_ioackin_vidOutput_TREADY or ap_reg_ppiten_pp0_it24 or exitcond1_fu_298_p2 or exitcond_fu_533_p2 or exitcond_reg_700 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
        end
        ap_ST_pp0_stg0_fsm_1 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it24) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it23)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == exitcond1_fu_298_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it24) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it23)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_102 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it21)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_622_pp0_it23) & (ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it24))) & ~(ap_const_lv1_0 == exitcond1_fu_298_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end
        end
        ap_ST_pp1_stg0_fsm_2 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond_fu_533_p2))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_2;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_const_logic_0 == ap_sig_ioackin_vidOutput_TREADY) & (ap_const_lv1_0 == exitcond_reg_700) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~(ap_const_lv1_0 == exitcond_fu_533_p2))) begin
                ap_NS_fsm = ap_ST_st29_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_2;
            end
        end
        ap_ST_st29_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end

/// ap_sig_bdd_102 assign process. ///
always @ (vidInput_TVALID or ap_reg_ppstg_tmp_reg_631_pp0_it20 or tmp_4_reg_682 or tmp_5_reg_686)
begin
    ap_sig_bdd_102 = (((vidInput_TVALID == ap_const_logic_0) & (ap_reg_ppstg_tmp_reg_631_pp0_it20 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_4_reg_682)) | ((vidInput_TVALID == ap_const_logic_0) & ~(ap_reg_ppstg_tmp_reg_631_pp0_it20 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_5_reg_686)));
end

/// ap_sig_bdd_262 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_262 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_288 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_288 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_0]);
end

/// ap_sig_bdd_342 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_342 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_42 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_42 = (ap_CS_fsm[ap_const_lv32_1] == ap_const_lv1_1);
end
assign exitcond1_fu_298_p2 = (j_phi_fu_239_p4 == ap_const_lv11_438? 1'b1: 1'b0);
assign exitcond_fu_533_p2 = (j1_reg_247 == ap_const_lv12_870? 1'b1: 1'b0);
assign grp_fu_258_p0 = tmp_2_reg_640;
assign grp_fu_258_p1 = ap_const_lv64_3FD2F684BDA12F68;
assign grp_fu_263_p0 = j_phi_fu_239_p4;
assign grp_fu_277_p2 = (line_r == ap_const_lv32_0? 1'b1: 1'b0);
assign isNeg_fu_354_p3 = sh_assign_fu_348_p2[ap_const_lv32_B];
assign j_1_fu_560_p2 = (ap_const_lv12_1 + j1_reg_247);
assign j_2_fu_304_p2 = (j_phi_fu_239_p4 + ap_const_lv11_1);
assign loc_V_1_fu_340_p1 = p_Val2_1_fu_319_p1[51:0];
assign loc_V_fu_330_p4 = {{p_Val2_1_fu_319_p1[ap_const_lv32_3E : ap_const_lv32_34]}};
assign p_Result_1_fu_380_p3 = {{ap_const_lv1_1}, {loc_V_1_reg_655}};
assign p_Val2_1_fu_319_p1 = x_assign_reg_645;
assign p_Val2_4_fu_436_p3 = ((isNeg_reg_660[0:0]===1'b1)? tmp_19_fu_422_p1: tmp_20_fu_426_p4);
assign p_Val2_7_i_i_fu_443_p2 = (ap_const_lv32_0 - p_Val2_4_reg_670);
assign p_Val2_s_fu_448_p3 = ((ap_reg_ppstg_p_Result_s_reg_650_pp0_it18[0:0]===1'b1)? p_Val2_7_i_i_fu_443_p2: p_Val2_4_reg_670);
assign sh_assign_1_cast_fu_391_p1 = $signed(sh_assign_1_reg_665);
assign sh_assign_1_fu_372_p3 = ((isNeg_fu_354_p3[0:0]===1'b1)? tmp_i_i_cast_fu_368_p1: sh_assign_fu_348_p2);
assign sh_assign_fu_348_p2 = ($signed(ap_const_lv12_C01) + $signed(tmp_i_i_i_cast2_fu_344_p1));
assign tmp_10_fu_554_p2 = (j1_reg_247 == ap_const_lv12_86F? 1'b1: 1'b0);
assign tmp_11_fu_571_p2 = (ap_const_lv32_1 + line_r);
assign tmp_12_fu_500_p1 = ap_reg_ppstg_j_reg_235_pp0_it21;
assign tmp_13_fu_491_p1 = ap_reg_ppstg_j_reg_235_pp0_it21;
assign tmp_14_fu_505_p1 = ap_reg_ppstg_j_reg_235_pp0_it22;
assign tmp_16_fu_516_p1 = grp_fu_277_p2;
assign tmp_17_fu_510_p2 = (ap_reg_ppstg_j_reg_235_pp0_it22 == ap_const_lv11_437? 1'b1: 1'b0);
assign tmp_18_fu_521_p2 = (line_r + ap_const_lv32_1);
assign tmp_19_fu_422_p1 = tmp_25_fu_414_p3;
assign tmp_1_i_i_cast_fu_398_p1 = $unsigned(sh_assign_1_cast_fu_391_p1);
assign tmp_1_i_i_fu_394_p1 = $unsigned(sh_assign_1_cast_fu_391_p1);
assign tmp_20_fu_426_p4 = {{tmp_4_i_i_fu_408_p2[ap_const_lv32_53 : ap_const_lv32_34]}};
assign tmp_21_fu_539_p1 = j1_reg_247[10:0];
assign tmp_25_fu_414_p3 = tmp_2_i_i_fu_402_p2[ap_const_lv32_34];
assign tmp_2_i_i_fu_402_p2 = p_Result_1_fu_380_p3 >> tmp_1_i_i_cast_fu_398_p1;
assign tmp_3_fu_566_p1 = grp_fu_277_p2;
assign tmp_4_fu_454_p2 = (p_Val2_s_reg_676 == prevIndex_fu_136? 1'b1: 1'b0);
assign tmp_4_i_i_fu_408_p2 = tmp_i_i_fu_387_p1 << tmp_1_i_i_fu_394_p1;
assign tmp_5_fu_466_p2 = (prevIndex_1_fu_132 == prevIndex_fu_136? 1'b1: 1'b0);
assign tmp_6_fu_583_p2 = ($signed(line_r) > $signed(32'b1110111111)? 1'b1: 1'b0);
assign tmp_8_fu_543_p2 = (ap_const_lv11_3C8 + tmp_21_fu_539_p1);
assign tmp_9_fu_549_p1 = tmp_8_fu_543_p2;
assign tmp_fu_310_p1 = j_phi_fu_239_p4[0:0];
assign tmp_i_i_11_fu_362_p2 = (ap_const_lv11_3FF - loc_V_fu_330_p4);
assign tmp_i_i_cast_fu_368_p1 = $signed(tmp_i_i_11_fu_362_p2);
assign tmp_i_i_fu_387_p1 = p_Result_1_fu_380_p3;
assign tmp_i_i_i_cast2_fu_344_p1 = loc_V_fu_330_p4;
assign vidOutput_TDATA = data_V_q1;
assign vidOutput_TDEST = ap_const_lv6_1;
assign vidOutput_TID = ap_const_lv5_0;
assign vidOutput_TKEEP = ap_const_lv2_1;
assign vidOutput_TSTRB = ap_const_lv2_1;


endmodule //rotatedUpscale

