-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.3
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity deltaFilter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    videoInA_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    videoInA_TVALID : IN STD_LOGIC;
    videoInA_TREADY : OUT STD_LOGIC;
    videoInA_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    videoInA_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    videoInA_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    videoInA_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    videoInA_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    videoInA_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    videoInB_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    videoInB_TVALID : IN STD_LOGIC;
    videoInB_TREADY : OUT STD_LOGIC;
    videoInB_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    videoInB_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    videoInB_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    videoInB_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    videoInB_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    videoInB_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    videoOut_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    videoOut_TVALID : OUT STD_LOGIC;
    videoOut_TREADY : IN STD_LOGIC;
    videoOut_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    videoOut_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    videoOut_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    videoOut_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    videoOut_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    videoOut_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of deltaFilter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "deltaFilter,hls_ip_2015_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=6.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.123750,HLS_SYN_LAT=641,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=13,HLS_SYN_LUT=79}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv10_280 : STD_LOGIC_VECTOR (9 downto 0) := "1010000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal i_1_fu_165_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_46 : BOOLEAN;
    signal exitcond_fu_159_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_57 : BOOLEAN;
    signal ap_sig_ioackin_videoOut_TREADY : STD_LOGIC;
    signal i_reg_148 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_72 : BOOLEAN;
    signal ap_reg_ioackin_videoOut_TREADY : STD_LOGIC := '0';
    signal r_V_fu_180_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_1_fu_192_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_cast_fu_184_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_1_cast_fu_196_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_fu_200_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal abscond_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_212_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_4_fu_218_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_4_cast_fu_226_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);


begin




    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_reg_ioackin_videoOut_TREADY assign process. --
    ap_reg_ioackin_videoOut_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_videoOut_TREADY <= ap_const_logic_0;
            else
                if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_159_p2 = ap_const_lv1_0) and not((ap_sig_bdd_57 or ((exitcond_fu_159_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY))))))) then 
                    ap_reg_ioackin_videoOut_TREADY <= ap_const_logic_0;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_159_p2 = ap_const_lv1_0) and not(ap_sig_bdd_57) and (ap_const_logic_1 = videoOut_TREADY)))) then 
                    ap_reg_ioackin_videoOut_TREADY <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- i_reg_148 assign process. --
    i_reg_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_159_p2 = ap_const_lv1_0) and not((ap_sig_bdd_57 or ((exitcond_fu_159_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY)))))) then 
                i_reg_148 <= i_1_fu_165_p2;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) then 
                i_reg_148 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm, exitcond_fu_159_p2, ap_sig_bdd_57, ap_sig_ioackin_videoOut_TREADY)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                ap_NS_fsm <= ap_ST_st2_fsm_1;
            when ap_ST_st2_fsm_1 => 
                if ((not((ap_sig_bdd_57 or ((exitcond_fu_159_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY)))) and not((exitcond_fu_159_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                elsif (((exitcond_fu_159_p2 = ap_const_lv1_0) and not((ap_sig_bdd_57 or ((exitcond_fu_159_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY)))))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    abscond_fu_206_p2 <= "1" when (signed(tmp_1_fu_200_p2) > signed(ap_const_lv9_0)) else "0";

    -- ap_rst_n_inv assign process. --
    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    -- ap_sig_bdd_46 assign process. --
    ap_sig_bdd_46_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_46 <= (ap_CS_fsm(1 downto 1) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_57 assign process. --
    ap_sig_bdd_57_assign_proc : process(videoInA_TVALID, videoInB_TVALID, exitcond_fu_159_p2)
    begin
                ap_sig_bdd_57 <= (((videoInA_TVALID = ap_const_logic_0) and (exitcond_fu_159_p2 = ap_const_lv1_0)) or ((exitcond_fu_159_p2 = ap_const_lv1_0) and (videoInB_TVALID = ap_const_logic_0)));
    end process;


    -- ap_sig_bdd_72 assign process. --
    ap_sig_bdd_72_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_72 <= (ap_const_lv1_1 = ap_CS_fsm(0 downto 0));
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_72)
    begin
        if (ap_sig_bdd_72) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st2_fsm_1 assign process. --
    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_bdd_46)
    begin
        if (ap_sig_bdd_46) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_ioackin_videoOut_TREADY assign process. --
    ap_sig_ioackin_videoOut_TREADY_assign_proc : process(videoOut_TREADY, ap_reg_ioackin_videoOut_TREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_videoOut_TREADY)) then 
            ap_sig_ioackin_videoOut_TREADY <= videoOut_TREADY;
        else 
            ap_sig_ioackin_videoOut_TREADY <= ap_const_logic_1;
        end if; 
    end process;

    exitcond_fu_159_p2 <= "1" when (i_reg_148 = ap_const_lv10_280) else "0";
    i_1_fu_165_p2 <= std_logic_vector(unsigned(i_reg_148) + unsigned(ap_const_lv10_1));
    r_V_1_cast_fu_196_p1 <= std_logic_vector(resize(unsigned(r_V_1_fu_192_p1),9));
    r_V_1_fu_192_p1 <= videoInB_TDATA(8 - 1 downto 0);
    r_V_cast_fu_184_p1 <= std_logic_vector(resize(unsigned(r_V_fu_180_p1),9));
    r_V_fu_180_p1 <= videoInA_TDATA(8 - 1 downto 0);
    tmp_1_fu_200_p2 <= std_logic_vector(unsigned(r_V_cast_fu_184_p1) - unsigned(r_V_1_cast_fu_196_p1));
    tmp_3_fu_212_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(tmp_1_fu_200_p2));
        tmp_4_cast_fu_226_p1 <= std_logic_vector(resize(signed(tmp_4_fu_218_p3),16));

    tmp_4_fu_218_p3 <= 
        tmp_1_fu_200_p2 when (abscond_fu_206_p2(0) = '1') else 
        tmp_3_fu_212_p2;

    -- videoInA_TREADY assign process. --
    videoInA_TREADY_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_159_p2, ap_sig_bdd_57, ap_sig_ioackin_videoOut_TREADY)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_159_p2 = ap_const_lv1_0) and not((ap_sig_bdd_57 or ((exitcond_fu_159_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY))))))) then 
            videoInA_TREADY <= ap_const_logic_1;
        else 
            videoInA_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    -- videoInB_TREADY assign process. --
    videoInB_TREADY_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_159_p2, ap_sig_bdd_57, ap_sig_ioackin_videoOut_TREADY)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_159_p2 = ap_const_lv1_0) and not((ap_sig_bdd_57 or ((exitcond_fu_159_p2 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_videoOut_TREADY))))))) then 
            videoInB_TREADY <= ap_const_logic_1;
        else 
            videoInB_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    videoOut_TDATA <= (tmp_4_cast_fu_226_p1 or ap_const_lv16_8000);
    videoOut_TDEST <= ap_const_lv6_1;
    videoOut_TID <= ap_const_lv5_0;
    videoOut_TKEEP <= ap_const_lv2_1;
    videoOut_TLAST <= videoInA_TLAST;
    videoOut_TSTRB <= ap_const_lv2_1;
    videoOut_TUSER <= ap_const_lv2_1;

    -- videoOut_TVALID assign process. --
    videoOut_TVALID_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_159_p2, ap_sig_bdd_57, ap_reg_ioackin_videoOut_TREADY)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_159_p2 = ap_const_lv1_0) and not(ap_sig_bdd_57) and (ap_const_logic_0 = ap_reg_ioackin_videoOut_TREADY)))) then 
            videoOut_TVALID <= ap_const_logic_1;
        else 
            videoOut_TVALID <= ap_const_logic_0;
        end if; 
    end process;

end behav;
