// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="simpleUpscale,hls_ip_2015_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=6.700000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.089000,HLS_SYN_LAT=1923,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=136,HLS_SYN_LUT=207}" *)

module simpleUpscale (
        ap_clk,
        ap_rst_n,
        videoIn_TDATA,
        videoIn_TVALID,
        videoIn_TREADY,
        videoIn_TKEEP,
        videoIn_TSTRB,
        videoIn_TUSER,
        videoIn_TLAST,
        videoIn_TID,
        videoIn_TDEST,
        videoOut_TDATA,
        videoOut_TVALID,
        videoOut_TREADY,
        videoOut_TKEEP,
        videoOut_TSTRB,
        videoOut_TUSER,
        videoOut_TLAST,
        videoOut_TID,
        videoOut_TDEST
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 5'b1;
parameter    ap_ST_st2_fsm_1 = 5'b10;
parameter    ap_ST_st3_fsm_2 = 5'b100;
parameter    ap_ST_st4_fsm_3 = 5'b1000;
parameter    ap_ST_st5_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv11_280 = 11'b1010000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv32_1E0 = 32'b111100000;
parameter    ap_const_lv11_780 = 11'b11110000000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_77F = 11'b11101111111;
parameter    ap_const_lv10_280 = 10'b1010000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv32_437 = 32'b10000110111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst_n;
input  [15:0] videoIn_TDATA;
input   videoIn_TVALID;
output   videoIn_TREADY;
input  [1:0] videoIn_TKEEP;
input  [1:0] videoIn_TSTRB;
input  [1:0] videoIn_TUSER;
input  [0:0] videoIn_TLAST;
input  [4:0] videoIn_TID;
input  [5:0] videoIn_TDEST;
output  [15:0] videoOut_TDATA;
output   videoOut_TVALID;
input   videoOut_TREADY;
output  [1:0] videoOut_TKEEP;
output  [1:0] videoOut_TSTRB;
output  [1:0] videoOut_TUSER;
output  [0:0] videoOut_TLAST;
output  [4:0] videoOut_TID;
output  [5:0] videoOut_TDEST;

reg videoIn_TREADY;
reg[15:0] videoOut_TDATA;
reg videoOut_TVALID;
reg[1:0] videoOut_TKEEP;
reg[1:0] videoOut_TSTRB;
reg[1:0] videoOut_TUSER;
reg[0:0] videoOut_TLAST;
reg[4:0] videoOut_TID;
reg[5:0] videoOut_TDEST;
reg    ap_rst_n_inv;
reg   [31:0] linenum = 32'b00000000000000000000000000000000;
reg   [31:0] linenum_load_reg_293;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm = 5'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_41;
wire   [0:0] tmp_fu_184_p2;
reg   [0:0] tmp_reg_298;
wire   [0:0] exitcond_fu_190_p2;
reg   [0:0] exitcond_reg_302;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_53;
reg    ap_sig_ioackin_videoOut_TREADY;
wire   [10:0] i_3_fu_196_p2;
wire   [9:0] tmp_2_fu_215_p2;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_71;
wire   [0:0] exitcond1_fu_209_p2;
reg    ap_sig_bdd_77;
wire   [10:0] i_4_fu_264_p2;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_89;
wire   [0:0] exitcond2_fu_251_p2;
wire   [31:0] tmp_9_fu_270_p2;
reg   [31:0] tmp_9_reg_327;
reg   [10:0] i_2_reg_146;
reg   [9:0] i_reg_157;
reg   [10:0] i_1_reg_168;
wire   [31:0] p_s_fu_280_p3;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_132;
wire   [0:0] tmp_4_fu_202_p2;
wire   [0:0] tmp_7_fu_257_p2;
reg    ap_reg_ioackin_videoOut_TREADY = 1'b0;
wire   [0:0] tmp_s_fu_275_p2;
reg   [4:0] ap_NS_fsm;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_videoOut_TREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_videoOut_TREADY
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_videoOut_TREADY <= ap_const_logic_0;
    end else begin
        if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0) & ~((exitcond_fu_190_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & (ap_const_lv1_0 == exitcond1_fu_209_p2)))))) begin
            ap_reg_ioackin_videoOut_TREADY <= ap_const_logic_0;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0) & (ap_const_logic_1 == videoOut_TREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~ap_sig_bdd_77 & (ap_const_logic_1 == videoOut_TREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2) & (ap_const_logic_1 == videoOut_TREADY)))) begin
            ap_reg_ioackin_videoOut_TREADY <= ap_const_logic_1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & (ap_const_lv1_0 == exitcond1_fu_209_p2))) & ~(ap_const_lv1_0 == exitcond1_fu_209_p2))) begin
        i_1_reg_168 <= ap_const_lv11_280;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2)))) begin
        i_1_reg_168 <= i_4_fu_264_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (tmp_fu_184_p2 == ap_const_lv1_0))) begin
        i_2_reg_146 <= ap_const_lv11_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0) & ~((exitcond_fu_190_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY)))) begin
        i_2_reg_146 <= i_3_fu_196_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(tmp_fu_184_p2 == ap_const_lv1_0))) begin
        i_reg_157 <= ap_const_lv10_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & (ap_const_lv1_0 == exitcond1_fu_209_p2))))) begin
        i_reg_157 <= tmp_2_fu_215_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((exitcond_fu_190_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY)))) begin
        exitcond_reg_302 <= exitcond_fu_190_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        linenum <= p_s_fu_280_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        linenum_load_reg_293 <= linenum;
        tmp_reg_298 <= tmp_fu_184_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2)) & (((tmp_reg_298 == ap_const_lv1_0) & ~(exitcond_reg_302 == ap_const_lv1_0)) | (~(tmp_reg_298 == ap_const_lv1_0) & ~(ap_const_lv1_0 == exitcond2_fu_251_p2))))) begin
        tmp_9_reg_327 <= tmp_9_fu_270_p2;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_41)
begin
    if (ap_sig_bdd_41) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_53)
begin
    if (ap_sig_bdd_53) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_71)
begin
    if (ap_sig_bdd_71) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_89)
begin
    if (ap_sig_bdd_89) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st5_fsm_4 assign process. ///
always @ (ap_sig_bdd_132)
begin
    if (ap_sig_bdd_132) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_ioackin_videoOut_TREADY assign process. ///
always @ (videoOut_TREADY or ap_reg_ioackin_videoOut_TREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_videoOut_TREADY)) begin
        ap_sig_ioackin_videoOut_TREADY = videoOut_TREADY;
    end else begin
        ap_sig_ioackin_videoOut_TREADY = ap_const_logic_1;
    end
end

/// videoIn_TREADY assign process. ///
always @ (ap_sig_ioackin_videoOut_TREADY or ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_209_p2 or ap_sig_bdd_77)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & (ap_const_lv1_0 == exitcond1_fu_209_p2))))) begin
        videoIn_TREADY = ap_const_logic_1;
    end else begin
        videoIn_TREADY = ap_const_logic_0;
    end
end

/// videoOut_TDATA assign process. ///
always @ (videoIn_TDATA or tmp_reg_298 or exitcond_fu_190_p2 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_209_p2 or ap_sig_bdd_77 or ap_sig_cseq_ST_st4_fsm_3 or exitcond2_fu_251_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~ap_sig_bdd_77)) begin
        videoOut_TDATA = videoIn_TDATA;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2)))) begin
        videoOut_TDATA = ap_const_lv16_0;
    end else begin
        videoOut_TDATA = 'bx;
    end
end

/// videoOut_TDEST assign process. ///
always @ (videoIn_TDEST or tmp_reg_298 or exitcond_fu_190_p2 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_209_p2 or ap_sig_bdd_77 or ap_sig_cseq_ST_st4_fsm_3 or exitcond2_fu_251_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~ap_sig_bdd_77)) begin
        videoOut_TDEST = videoIn_TDEST;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2)))) begin
        videoOut_TDEST = ap_const_lv6_1;
    end else begin
        videoOut_TDEST = 'bx;
    end
end

/// videoOut_TID assign process. ///
always @ (videoIn_TID or tmp_reg_298 or exitcond_fu_190_p2 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_209_p2 or ap_sig_bdd_77 or ap_sig_cseq_ST_st4_fsm_3 or exitcond2_fu_251_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~ap_sig_bdd_77)) begin
        videoOut_TID = videoIn_TID;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2)))) begin
        videoOut_TID = ap_const_lv5_0;
    end else begin
        videoOut_TID = 'bx;
    end
end

/// videoOut_TKEEP assign process. ///
always @ (videoIn_TKEEP or tmp_reg_298 or exitcond_fu_190_p2 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_209_p2 or ap_sig_bdd_77 or ap_sig_cseq_ST_st4_fsm_3 or exitcond2_fu_251_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~ap_sig_bdd_77)) begin
        videoOut_TKEEP = videoIn_TKEEP;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2)))) begin
        videoOut_TKEEP = ap_const_lv2_1;
    end else begin
        videoOut_TKEEP = 'bx;
    end
end

/// videoOut_TLAST assign process. ///
always @ (tmp_reg_298 or exitcond_fu_190_p2 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_209_p2 or ap_sig_bdd_77 or ap_sig_cseq_ST_st4_fsm_3 or exitcond2_fu_251_p2 or tmp_4_fu_202_p2 or tmp_7_fu_257_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2))) begin
        videoOut_TLAST = tmp_7_fu_257_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~ap_sig_bdd_77)) begin
        videoOut_TLAST = ap_const_lv1_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0))) begin
        videoOut_TLAST = tmp_4_fu_202_p2;
    end else begin
        videoOut_TLAST = 'bx;
    end
end

/// videoOut_TSTRB assign process. ///
always @ (videoIn_TSTRB or tmp_reg_298 or exitcond_fu_190_p2 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_209_p2 or ap_sig_bdd_77 or ap_sig_cseq_ST_st4_fsm_3 or exitcond2_fu_251_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~ap_sig_bdd_77)) begin
        videoOut_TSTRB = videoIn_TSTRB;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2)))) begin
        videoOut_TSTRB = ap_const_lv2_1;
    end else begin
        videoOut_TSTRB = 'bx;
    end
end

/// videoOut_TUSER assign process. ///
always @ (videoIn_TUSER or tmp_reg_298 or exitcond_fu_190_p2 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_209_p2 or ap_sig_bdd_77 or ap_sig_cseq_ST_st4_fsm_3 or exitcond2_fu_251_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~ap_sig_bdd_77)) begin
        videoOut_TUSER = videoIn_TUSER;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2)))) begin
        videoOut_TUSER = ap_const_lv2_1;
    end else begin
        videoOut_TUSER = 'bx;
    end
end

/// videoOut_TVALID assign process. ///
always @ (tmp_reg_298 or exitcond_fu_190_p2 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or exitcond1_fu_209_p2 or ap_sig_bdd_77 or ap_sig_cseq_ST_st4_fsm_3 or exitcond2_fu_251_p2 or ap_reg_ioackin_videoOut_TREADY)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_fu_190_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_reg_ioackin_videoOut_TREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == exitcond1_fu_209_p2) & ~ap_sig_bdd_77 & (ap_const_logic_0 == ap_reg_ioackin_videoOut_TREADY)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2) & (ap_const_logic_0 == ap_reg_ioackin_videoOut_TREADY)))) begin
        videoOut_TVALID = ap_const_logic_1;
    end else begin
        videoOut_TVALID = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or tmp_fu_184_p2 or tmp_reg_298 or exitcond_fu_190_p2 or exitcond_reg_302 or ap_sig_ioackin_videoOut_TREADY or exitcond1_fu_209_p2 or ap_sig_bdd_77 or exitcond2_fu_251_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(tmp_fu_184_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (((exitcond_fu_190_p2 == ap_const_lv1_0) & ~((exitcond_fu_190_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY)))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else if ((~((exitcond_fu_190_p2 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY)) & ~(exitcond_fu_190_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if (((ap_const_lv1_0 == exitcond1_fu_209_p2) & ~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & (ap_const_lv1_0 == exitcond1_fu_209_p2))))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else if ((~(ap_sig_bdd_77 | ((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & (ap_const_lv1_0 == exitcond1_fu_209_p2))) & ~(ap_const_lv1_0 == exitcond1_fu_209_p2))) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            if ((~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2) & ~((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2)))) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else if ((~((ap_const_logic_0 == ap_sig_ioackin_videoOut_TREADY) & ~(tmp_reg_298 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond2_fu_251_p2)) & (((tmp_reg_298 == ap_const_lv1_0) & ~(exitcond_reg_302 == ap_const_lv1_0)) | (~(tmp_reg_298 == ap_const_lv1_0) & ~(ap_const_lv1_0 == exitcond2_fu_251_p2))))) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end

/// ap_sig_bdd_132 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_132 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_41 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_41 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_53 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_53 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_71 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_71 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_77 assign process. ///
always @ (videoIn_TVALID or exitcond1_fu_209_p2)
begin
    ap_sig_bdd_77 = ((videoIn_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == exitcond1_fu_209_p2));
end

/// ap_sig_bdd_89 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_89 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end
assign exitcond1_fu_209_p2 = (i_reg_157 == ap_const_lv10_280? 1'b1: 1'b0);
assign exitcond2_fu_251_p2 = (i_1_reg_168 == ap_const_lv11_780? 1'b1: 1'b0);
assign exitcond_fu_190_p2 = (i_2_reg_146 == ap_const_lv11_780? 1'b1: 1'b0);
assign i_3_fu_196_p2 = (i_2_reg_146 + ap_const_lv11_1);
assign i_4_fu_264_p2 = (i_1_reg_168 + ap_const_lv11_1);
assign p_s_fu_280_p3 = ((tmp_s_fu_275_p2[0:0]===1'b1)? ap_const_lv32_0: tmp_9_reg_327);
assign tmp_2_fu_215_p2 = (i_reg_157 + ap_const_lv10_1);
assign tmp_4_fu_202_p2 = (i_2_reg_146 == ap_const_lv11_77F? 1'b1: 1'b0);
assign tmp_7_fu_257_p2 = (i_1_reg_168 == ap_const_lv11_77F? 1'b1: 1'b0);
assign tmp_9_fu_270_p2 = (linenum_load_reg_293 + ap_const_lv32_1);
assign tmp_fu_184_p2 = ($signed(linenum) < $signed(32'b111100000)? 1'b1: 1'b0);
assign tmp_s_fu_275_p2 = ($signed(tmp_9_reg_327) > $signed(32'b10000110111)? 1'b1: 1'b0);


endmodule //simpleUpscale

