# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivadoprojects/armqp/armqp_math_tester/armqp_math_tester.srcs/sources_1/ip/translate/translate.xci
# IP: The module: 'translate' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivadoprojects/armqp/armqp_math_tester/armqp_math_tester.srcs/sources_1/ip/translate/translate_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'translate'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/vivadoprojects/armqp/armqp_math_tester/armqp_math_tester.srcs/sources_1/ip/translate/translate.xci
# IP: The module: 'translate' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivadoprojects/armqp/armqp_math_tester/armqp_math_tester.srcs/sources_1/ip/translate/translate_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'translate'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
