# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivadoprojects/armqp/armqp_math_tester/armqp_math_tester.cache/wt [current_project]
set_property parent.project_path D:/vivadoprojects/armqp/armqp_math_tester/armqp_math_tester.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files -quiet D:/vivadoprojects/armqp/armqp_math_tester/armqp_math_tester.runs/rotate_synth_1/rotate.dcp
set_property used_in_implementation false [get_files D:/vivadoprojects/armqp/armqp_math_tester/armqp_math_tester.runs/rotate_synth_1/rotate.dcp]
add_files -quiet D:/vivadoprojects/armqp/armqp_math_tester/armqp_math_tester.runs/translate_synth_1/translate.dcp
set_property used_in_implementation false [get_files D:/vivadoprojects/armqp/armqp_math_tester/armqp_math_tester.runs/translate_synth_1/translate.dcp]
read_verilog -library xil_defaultlib {
  D:/vivadoprojects/armqp/src/hdl/barrel_math_hdl.v
  D:/vivadoprojects/armqp/src/hdl/math_tester.v
}
synth_design -top math_tester -part xc7z020clg484-1
write_checkpoint -noxdef math_tester.dcp
catch { report_utilization -file math_tester_utilization_synth.rpt -pb math_tester_utilization_synth.pb }
